# Generated by Django 2.2.4 on 2019-08-09 07:22

from django.db import migrations, models
import exel.models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aversflat',
            name='file',
            field=models.FileField(upload_to=exel.models.user_directory_path),
        ),
    ]
