# Generated by Django 2.2.4 on 2019-08-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0002_auto_20190809_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputExel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_file', models.FileField(upload_to='')),
            ],
        ),
    ]
